version: '3'

services:
  onomy:
    # docker build -t onomy/onomy-devnet:local  -f Dockerfile ../../
    image: onomy/onomy-devnet:local
    restart: on-failure
    container_name: onomy-devnet-local
    environment:
      ETH_RPC_ADDRESS: https://eth-rinkeby.alchemyapi.io/v2/...
    # volumes:
      # uncomment to update onomy config in runtime
      # - ./scripts:/root/home/scripts
      # uncomment to update onomy config in runtime
      # - ./.onomy:/root/.onomy
    ports:
      # onomy
      - 26656:26656
      - 26657:26657
      - 1317:1317 # swagger
      - 61278:61278
      - 9090:9090
      - 8000:8000 # fauset